### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by kura6789** [wojtazk/allegrolokalnie-auction-bot#9]
Hi, ty for sharing this project but how u bypass blocking? Happened in first try:
![Bez tytułu](https://github.com/wojtazk/allegrolokalnie-auction-bot/assets/28402838/0eee58c9-3dc3-489f-96db-b6386afb5bb3)

**Comment by wojtazk** [comment]
Mnie blokuje zazwyczaj jak VPN'a używam:
![image](https://github.com/wojtazk/allegrolokalnie-auction-bot/assets/48928433/f40194e0-6206-48ab-a304-84c77752b1a9)

Jak VPN jest wyłączony, to nie ma do mnie żadnego problemu i się normalnie loguje:
![image](https://github.com/wojtazk/allegrolokalnie-auction-bot/assets/48928433/9016f839-3774-4879-8e3e-bf99d266f5e6)

<br>

Możesz popróbować z róznych sieci się zalogować, np.  hotspot z telefonu itd, może tam cię nie będzie blokowało
